export const DELAY_OF_INCREASING_OF_ENERGY = 1000
export const ENERGY_TO_INCREASE = 1
export const MAX_AUTOBOT_MINING_TIME_HOURS = 3
export const REWARD_PARENT_REFERRAL = 2000
export const REWARD_REFERRAL = 1000
export const MAX_BOOST_NUMBER = 3
export const DELAY_OF_TOKENS_SYNC = 500
